import type { Metadata } from "next";
import type { Meta } from "@/lib/content/types";
import { SITE_NAME, SITE_URL } from "@/lib/site";
import { htmlLang, type Locale } from "@/lib/i18n/config";
import { otherLocale, routes, type PageKey } from "@/lib/i18n/routes";
import { EVENT_CLOSING_ISO, EVENT_OPENING_ISO } from "@/lib/content/event";

/** Open Graph locale codes (underscored region form). */
const ogLocale: Record<Locale, string> = {
  pt: "pt_PT",
  en: "en_US",
};

/**
 * The shared social share image, generated by the `/og` route. Referenced by
 * absolute URL (not the `opengraph-image` file convention) because, with two
 * root layouts inside route groups, there's no app-root layout to provide
 * `metadataBase` for the convention to resolve against.
 */
const ogImage = {
  url: new URL("/og", SITE_URL).toString(),
  width: 1200,
  height: 630,
  alt: "Semana Solidária U.Porto — 21 a 26 de setembro de 2026",
};

/** Default site description per locale, used by the root layouts. */
const rootDescription: Record<Locale, string> = {
  pt: "Semana da Cidadania, Voluntariado e Responsabilidade Social da Universidade do Porto. 21 a 26 de setembro de 2026.",
  en: "Week of Citizenship, Volunteering and Social Responsibility at the University of Porto. 21–26 September 2026.",
};

/** Absolute URL for a page in a given locale. */
function pageUrl(locale: Locale, pageKey: PageKey): string {
  return new URL(routes[locale][pageKey], SITE_URL).toString();
}

/**
 * hreflang alternates for a page: both locales plus `x-default` (→ Portuguese,
 * the default locale). Search engines use this to serve the right language.
 */
function languageAlternates(pageKey: PageKey): Record<string, string> {
  return {
    [htmlLang.pt]: pageUrl("pt", pageKey),
    [htmlLang.en]: pageUrl("en", pageKey),
    "x-default": pageUrl("pt", pageKey),
  };
}

/**
 * Per-page metadata: canonical URL, hreflang alternates, Open Graph and
 * Twitter cards. The OG/Twitter *images* are supplied automatically by the
 * `opengraph-image`/`twitter-image` file conventions and merged in by Next.
 */
export function buildMetadata(
  meta: Meta,
  { locale, pageKey }: { locale: Locale; pageKey: PageKey },
): Metadata {
  const url = pageUrl(locale, pageKey);
  return {
    title: meta.title,
    description: meta.description,
    alternates: {
      canonical: url,
      languages: languageAlternates(pageKey),
    },
    openGraph: {
      type: "website",
      siteName: SITE_NAME,
      title: meta.title,
      description: meta.description,
      url,
      locale: ogLocale[locale],
      alternateLocale: ogLocale[otherLocale[locale]],
      images: [ogImage],
    },
    twitter: {
      card: "summary_large_image",
      title: meta.title,
      description: meta.description,
      images: [ogImage.url],
    },
  };
}

/**
 * Root-layout metadata for a locale: sets `metadataBase` (so every relative
 * canonical/OG URL resolves) and sensible site-wide defaults that pages inherit
 * when they don't export their own.
 */
export function buildRootMetadata(locale: Locale): Metadata {
  return {
    metadataBase: new URL(SITE_URL),
    title: SITE_NAME,
    description: rootDescription[locale],
    applicationName: SITE_NAME,
    openGraph: {
      type: "website",
      siteName: SITE_NAME,
      title: SITE_NAME,
      description: rootDescription[locale],
      url: pageUrl(locale, "home"),
      locale: ogLocale[locale],
      alternateLocale: ogLocale[otherLocale[locale]],
      images: [ogImage],
    },
    twitter: { card: "summary_large_image", images: [ogImage.url] },
  };
}

/**
 * Structured data (JSON-LD) for the homepage: the event itself plus the
 * organising body. Rendered via `<JsonLd>` so search engines can surface rich
 * results. Returns an array — valid JSON-LD for multiple top-level items.
 */
export function homeJsonLd(locale: Locale, description: string): Record<string, unknown>[] {
  const organization = {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: "ReVIReS — Rede de Voluntariado, Inclusão e Responsabilidade Social da U.Porto",
    alternateName: "ReVIReS",
    url: "https://www.up.pt/",
    parentOrganization: {
      "@type": "CollegeOrUniversity",
      name: "Universidade do Porto",
      url: "https://www.up.pt/",
    },
  };

  const event = {
    "@context": "https://schema.org",
    "@type": "Event",
    name: SITE_NAME,
    description,
    startDate: EVENT_OPENING_ISO,
    endDate: EVENT_CLOSING_ISO,
    eventStatus: "https://schema.org/EventScheduled",
    eventAttendanceMode: "https://schema.org/OfflineEventAttendanceMode",
    inLanguage: htmlLang[locale],
    url: pageUrl(locale, "home"),
    image: ogImage.url,
    location: {
      "@type": "Place",
      name: "Universidade do Porto",
      address: {
        "@type": "PostalAddress",
        addressLocality: "Porto",
        addressCountry: "PT",
      },
    },
    organizer: {
      "@type": "Organization",
      name: "ReVIReS — U.Porto",
      url: "https://www.up.pt/",
    },
  };

  return [event, organization];
}
